Repository GSG-FC02/Urban-Natural-G6, pull requests merged in 2021-03, with the labels that each got.

#3 create folders
  Css/style.css
  Html/before-visit-info.html
  Html/calendar.html
  Html/contact-info.html
  Html/index.html
  Html/landing-page.html
  Html/self declaration.html
  Html/successful-booking.html
  Images/image.png
Labels: in-progress

#14 modifay Readme
  README.md
Labels: in-progress

#7 creat html file , css file and image file
  Css/style.css
  Html/index.html
  Html/landing-page.html
  index.html
Labels: approved

#9 modify self declartion html and css files
  Css/style.css
  Html/self declaration.html
Labels: approved

#11 Create calendar
  Css/style.css
  Html/calendar.html
Labels: awaiting-review

#6 create successful booking page
  Css/style.css
  Html/successful-booking.html
  Images/icon.png
Labels: approved
